version: '3.3'
services:
  postgresql:
    image: postgres:12.5-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  eyespotted-frontend:
    image: farosbelgium/eyespotted-frontend:latest
    ports:
      - "4200:80"
